apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kong.dblessConfig.configMap }}
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    services:
      # orion rate-limited
      - host: "fiware-orion-ld"
        name: "orion-limited"
        port: 1026
        protocol: http

        routes:
          - name: orion-limited
            paths:
              - /limited
            strip_path: true

        plugins:
          - name: rate-limiting
            config: 
              minute: 3

      # keycloak example
      - host: "fiware-orion-ld"
        name: "orion-keycloak"
        port: 1026
        protocol: http

        routes:
          - name: orion-keycloak
            paths:
              - /keycloak
            strip_path: true

        plugins:
          - name: prometheus

          - name: rate-limiting
            config: 
              minute: 30

          - name: pep-plugin
            config:
              authorizationendpointtype: Keycloak
              authorizationendpointaddress: http://fiware-keycloak:80
              keycloakrealm: fiware-server
              keycloakclientid: orion-pep
              keycloakclientsecret: 978ad148-d99b-406d-83fc-578597290a79

          - name: request-transformer
            config:
              remove:
                headers:
                  - Authorization
                  - authorization
